image: jsii/superchain
tasks:
  - init: git clone https://github.com/aws/aws-cdk.git && cd aws-cdk && ./build.sh --skip-test --no-bail

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
