FROM pahud/aws-cdk-autobuild:latest as builder

FROM node:lts-alpine as runtime

WORKDIR /app

COPY --from=builder /app/node_modules/.bin /usr/local/bin/
COPY --from=builder /app /app/

ENTRYPOINT ['/usr/local/bin/cdk']

