FROM pahud/aws-cdk-autobuild:latest

WORKDIR /app

RUN npm i --save-dev lerna && npm i -g aws-cdk && yarn install

ENV USER cdkuser

ENV PS1 '\[\033[01;32m\]${USER}(cdk-docker)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)" 2>/dev/null) $'

ENV HOME /home/cdkuser

COPY lr.alias /tmp/

RUN useradd -ms /bin/bash -u 501 -d /home/cdkuser cdkuser

RUN cat /tmp/lr.alias >> /home/cdkuser/.bashrc

USER cdkuser

ENTRYPOINT []
